export interface RepoInfo {
  owner: string;
  name: string;
  fullName: string;
  description: string | null;
  language: string | null;
  stars: number;
  forks: number;
  defaultBranch: string;
  updatedAt: string;
  createdAt: string;
  isPrivate: boolean;
  topics: string[];
  url: string;
}

export interface FileNode {
  path: string;
  name: string;
  type: "file" | "dir";
  size?: number;
}

export interface PRSummary {
  number: number;
  title: string;
  body: string | null;
  state: string;
  mergedAt: string | null;
  createdAt: string;
  closedAt: string | null;
  author: string;
  labels: string[];
  additions: number;
  deletions: number;
  changedFiles: number;
}

export interface CommitSummary {
  sha: string;
  message: string;
  author: string;
  date: string;
  additions?: number;
  deletions?: number;
}

export interface FeatureMapping {
  name: string;
  description: string;
  files: string[];
  businessPurpose: string;
  category:
    | "acquisition"
    | "activation"
    | "retention"
    | "revenue"
    | "admin"
    | "infrastructure";
}

export interface Milestone {
  date: string;
  title: string;
  description: string;
  prs: number[];
  theme: string;
  isInferred: boolean;
}

export interface Entrypoint {
  path: string;
  reason: string;
  priority: "high" | "medium" | "low";
  type: "file" | "service" | "flow";
}

export interface TimelineData {
  prs: PRSummary[];
  commits: CommitSummary[];
  milestones: Milestone[];
  milestoneSummaries?: Record<string, string>; // date key -> AI summary
}

export interface Citation {
  id: string;
  filePath: string;
  startLine?: number;
  endLine?: number;
  snippet?: string;
}

export interface CodemapNode {
  id: string;
  title: string;
  description: string;
  children: CodemapNode[];
  citations: Citation[];
  diagram?: string;
}

export interface Codemap {
  title: string;
  summary: string;
  nodes: CodemapNode[];
}

export interface ProjectBrief {
  id: string;
  repoInfo: RepoInfo;
  generatedAt: string;

  // What this project is
  overview: {
    summary: string;
    likelyUser: string;
    valueProposition: string;
    majorFlows: string[];
    stats: {
      totalFiles: number;
      totalPRs: number;
      totalCommits: number;
      topLanguages: string[];
    };
  };

  // How it is built
  architecture: {
    stack: string[];
    dependencies: Record<string, string>;
    apis: string[];
    integrations: string[];
    summary: string;
    keyModules: { name: string; path: string; purpose: string }[];
  };

  // Core features
  features: FeatureMapping[];

  // Business context
  businessContext: {
    targetUser: string;
    businessModel: string;
    valueProposition: string;
    featureClassification: FeatureMapping[];
    isInferred: boolean;
  };

  // Evolution timeline
  timeline: Milestone[];

  // Where to start
  entrypoints: Entrypoint[];

  // Hierarchical code understanding (generated by agentic analysis)
  codemap?: Codemap;

  // AI-generated mermaid diagrams (from synthesis model)
  diagrams?: {
    overview?: string;
    architecture?: string;
    stack?: string;
    dataFlow?: string;
    entityRelationship?: string;
  };

  // Structured flow explanation for the overview section
  overviewExplanation?: {
    introduction: string;
    steps: {
      title: string;
      description: string;
      codeRefs: { filePath: string; line?: number; label: string }[];
    }[];
  };

  // Enriched timeline data for visualizations
  timelineData?: TimelineData;

  // Analysis depth used to produce this brief
  depth?: "standard" | "deep";

  // The commit SHA the analysis was pinned to. Used by chat RAG retrieval to
  // scope semantic search against the matching slice of repo_embeddings.
  commitSha?: string;
}

export interface ChatMessage {
  id: string;
  role: "user" | "assistant";
  content: string;
  timestamp: string;
}

export interface ChatSession {
  briefId: string;
  messages: ChatMessage[];
}

export interface AnalysisStatus {
  step:
    | "connecting"
    | "fetching-tree"
    | "fetching-prs"
    | "fetching-commits"
    | "reading-files"
    | "generating-brief"
    | "complete"
    | "error";
  progress: number;
  message: string;
}
